// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atzyqbztemcruudrdutr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0enlxYnp0ZW1jcnV1ZHJkdXRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwODEyMzcsImV4cCI6MjA2NDY1NzIzN30.IMe-99ZyHnUoR8r8KmNDgGHL4t1zWKyKWW9c_i22M80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);